# Generated by Django 4.2.4 on 2024-11-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_type',
            field=models.CharField(choices=[('board1', '일반게시판'), ('board2', '챌린지게시판1'), ('board3', '챌린지게시판2')], default='board1', max_length=20),
        ),
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board/images/'),
        ),
    ]
