# Generated by Django 4.2.4 on 2024-11-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_balance_deposit_user_balance_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance_saving',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
